apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: nztav8w3v-dotnet-basic 
  janus-idp.io/tekton: nztav8w3v-dotnet-basic
  backstage.io/kubernetes-id: nztav8w3v-dotnet-basic
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: nztav8w3v-dotnet-basic
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  